// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ips.sql

package database

import (
	"context"
)

const getAllAssigned = `-- name: GetAllAssigned :many
SELECT id, address, is_used, subnet_id FROM ips
WHERE subnet_id = ?1
AND is_used = TRUE
ORDER BY address ASC
`

func (q *Queries) GetAllAssigned(ctx context.Context, subnetID int64) ([]Ip, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssigned, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ip
	for rows.Next() {
		var i Ip
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.IsUsed,
			&i.SubnetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFreeIP = `-- name: GetFreeIP :one
SELECT id, address, is_used, subnet_id FROM ips
WHERE subnet_id = ?1
AND is_used = FALSE
ORDER BY address ASC
LIMIT 1
`

func (q *Queries) GetFreeIP(ctx context.Context, subnetID int64) (Ip, error) {
	row := q.db.QueryRowContext(ctx, getFreeIP, subnetID)
	var i Ip
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.IsUsed,
		&i.SubnetID,
	)
	return i, err
}

const releaseIP = `-- name: ReleaseIP :exec
UPDATE ips
SET is_used = 0
WHERE id = ?1
`

func (q *Queries) ReleaseIP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, releaseIP, id)
	return err
}

const reserveIP = `-- name: ReserveIP :exec
UPDATE ips
SET is_used = 1
WHERE id = ?1
`

func (q *Queries) ReserveIP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, reserveIP, id)
	return err
}
