// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Ip struct {
	ID       int64
	Address  string
	IsUsed   int64
	SubnetID int64
}

type Subnet struct {
	ID            int64
	Name          string
	NetworkPrefix string
	Cidr          int64
}
