// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subnets.sql

package database

import (
	"context"
)

const getSubnet = `-- name: GetSubnet :one
SELECT id, name, network_prefix, cidr FROM subnets WHERE id = ?
`

func (q *Queries) GetSubnet(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnet, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NetworkPrefix,
		&i.Cidr,
	)
	return i, err
}

const getSubnetByName = `-- name: GetSubnetByName :one
SELECT id, name, network_prefix, cidr FROM subnets WHERE name = ?
`

func (q *Queries) GetSubnetByName(ctx context.Context, name string) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByName, name)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NetworkPrefix,
		&i.Cidr,
	)
	return i, err
}

const getSubnets = `-- name: GetSubnets :many
SELECT id, name, network_prefix, cidr FROM subnets
`

func (q *Queries) GetSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NetworkPrefix,
			&i.Cidr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newSubnet = `-- name: NewSubnet :exec
INSERT INTO subnets (name, network_prefix, cidr) VALUES (?, ?, ?)
`

type NewSubnetParams struct {
	Name          string
	NetworkPrefix string
	Cidr          int64
}

func (q *Queries) NewSubnet(ctx context.Context, arg NewSubnetParams) error {
	_, err := q.db.ExecContext(ctx, newSubnet, arg.Name, arg.NetworkPrefix, arg.Cidr)
	return err
}
